DNA_dropout: 0.25
DNA_kernel_size: 10
calculate_val_tf_loss: true
final_embeddings_size: 128
initial_prot_kernel_size: 1
kmer_embedding_size: 32
learning_rate: 1.0e-05
linear_layer_size_prot: 64
num_DNA_filters: 90
num_kmers: 8000
num_prot_filters: 50
prot_kernel_size: 10
protein_dropout: 0.25
seq_len: 65536
