DNA_branch_path: /home/data/shared/natant/Results/DNA_model_transfer/DNA_small/DNA-model-20230413_15:52:01-epoch=17-val_loss=0.03.ckpt
DNA_dropout: 0.25
DNA_kernel_size: 10
calculate_val_tf_loss: true
final_embeddings_size: 128
initial_prot_kernel_size: 1
learning_rate: 1.0e-05
linear_layer_size_prot: 64
num_DNA_filters: 30
num_prot_filters: 50
prot_embedding_dim: 480
prot_kernel_size: 10
protein_dropout: 0.25
seq_len: 65536
