wandb_version: 1

DNA_kernel_size:
  desc: null
  value: 10
Model:
  desc: null
  value: DNA
_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1671456343.189399
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      3:
      - 19
      - 23
      4: 3.10.6
      5: 0.13.5
      6: 4.24.0
      8:
      - 5
dropout:
  desc: null
  value: 0.25
linear_layer_size:
  desc: null
  value: 400
num_DNA_filters:
  desc: null
  value: 200
num_classes:
  desc: null
  value: 321
num_linear_layers:
  desc: null
  value: 3
seq_len:
  desc: null
  value: 1024
