DNA_dropout: 0.25
DNA_kernel_size: 10
calculate_val_tf_loss: true
final_embeddings_size: 128
initial_prot_kernel_size: 1
learning_rate: 0.001
linear_layer_size_prot: 64
num_DNA_filters: 60
num_prot_filters: 50
prot_embedding_dim: 480
prot_kernel_size: 10
protein_dropout: 0.25
seq_len: 65536
